# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Extract to global variables those variables most
# susceptible to be overridden.
global:
  image:
    nginx: ""
  dataConfigMap:


replicaCount: 1
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0


deployment:
  labels:
    tier: web
  image:
    tag: latest
    pullPolicy: Always
  ports:
    - name: http
      containerPort: 80
  probes:
    livenessEnabled: true
    readinessEnabled: true
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 50m
      memory: 50Mi


service:
    enabled: true
    type: NodePort
    externalPort: 80
    internalPort: 8000


configMap:
    enableBasicAuth: "False"
    enableHttpsForce: "False"
    force3WRedirect: "True"
